 const TYPES ={
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_ONE_FROM_CART:"REMOVE_ONE_FROM_CART",
    REMOVE_ALL_FROM_CART:"REMOVE_ALL_FROM_CART",
    SEND_ORDER: "SEND_ORDER",
    TOTAL_CART:"TOTAL_CART",
    
}
export default TYPES;